version: '3'
services:
  develop:
    build: .
    volumes:
     - .:/root
     - /tmp/.X11-unix/X0:/tmp/.X11-unix/X0
    ports:
     - '9000-9010:9000-9010'
    environment:
     - TZ=America/Sao_Paulo
     - DISPLAY=$DISPLAY
    network_mode: 'host'
